--[[
    Haiku OS Build System - xmake configuration

    Equivalent to Jamrules + build/jam/* for the xmake build system.

    Usage:
        ./configure4xmake --build-cross-tools x86_64 --cross-tools-source buildtools -j8
        xmake f -c                    # Configure
        xmake                         # Build
        xmake libbe_build             # Build specific target
]]

-- ============================================================================
-- Project Configuration
-- ============================================================================

set_xmakever("2.7.0")
set_project("haiku")
set_version("1.0.0")
set_languages("c11", "c++17")

-- ============================================================================
-- Path Configuration
-- ============================================================================

HAIKU_TOP = os.projectdir()
HAIKU_OUTPUT_DIR = path.join(HAIKU_TOP, "spawned")

set_config("haiku_top", HAIKU_TOP)
set_config("haiku_output_dir", HAIKU_OUTPUT_DIR)
set_config("buildir", HAIKU_OUTPUT_DIR)

-- ============================================================================
-- Load XmakeConfig.lua (generated by configure4xmake)
-- ============================================================================

local xmake_config_path = path.join(HAIKU_OUTPUT_DIR, "build", "XmakeConfig.lua")
if os.isfile(xmake_config_path) then
    includes(xmake_config_path)
else
    print("Warning: XmakeConfig.lua not found. Run ./configure4xmake first.")
end

-- ============================================================================
-- Path Helper Functions
-- ============================================================================

function get_haiku_top()
    return HAIKU_TOP
end

function get_haiku_output_dir()
    return HAIKU_OUTPUT_DIR
end

function get_haiku_tools_dir()
    return path.join(HAIKU_OUTPUT_DIR, "tools")
end

function get_haiku_objects_dir()
    return path.join(HAIKU_OUTPUT_DIR, "objects")
end

-- ============================================================================
-- Rule Includes (from build/xmake/rules/)
-- ============================================================================

local rules_dir = path.join(HAIKU_TOP, "build", "xmake", "rules")

includes(path.join(rules_dir, "HelperRules.lua"))
includes(path.join(rules_dir, "BuildFeatureRules.lua"))
includes(path.join(rules_dir, "ConfigRules.lua"))
includes(path.join(rules_dir, "FileRules.lua"))
includes(path.join(rules_dir, "ArchitectureRules.lua"))
includes(path.join(rules_dir, "HeadersRules.lua"))
includes(path.join(rules_dir, "MainBuildRules.lua"))
includes(path.join(rules_dir, "BeOSRules.lua"))
includes(path.join(rules_dir, "KernelRules.lua"))
includes(path.join(rules_dir, "BootRules.lua"))
includes(path.join(rules_dir, "PackageRules.lua"))
includes(path.join(rules_dir, "ImageRules.lua"))
includes(path.join(rules_dir, "CDRules.lua"))
includes(path.join(rules_dir, "LocaleRules.lua"))
includes(path.join(rules_dir, "MathRules.lua"))
includes(path.join(rules_dir, "MiscRules.lua"))
includes(path.join(rules_dir, "RepositoryRules.lua"))
includes(path.join(rules_dir, "TestsRules.lua"))
includes(path.join(rules_dir, "SystemLibraryRules.lua"))

-- ============================================================================
-- Configuration Includes (from build/xmake/config/)
-- ============================================================================

local config_dir = path.join(HAIKU_TOP, "build", "xmake", "config")

if os.isfile(path.join(config_dir, "BuildSetup.lua")) then
    includes(path.join(config_dir, "BuildSetup.lua"))
end
if os.isfile(path.join(config_dir, "BuildFeatures.lua")) then
    includes(path.join(config_dir, "BuildFeatures.lua"))
end
if os.isfile(path.join(config_dir, "UserBuildConfig.lua")) then
    includes(path.join(config_dir, "UserBuildConfig.lua"))
end

-- ============================================================================
-- Platform Configuration
-- ============================================================================

if is_plat("haiku") then
    set_toolchains("gcc")
    add_defines("_GNU_SOURCE", "__HAIKU__")
elseif is_plat("host") or is_host("linux", "macosx", "bsd") then
    set_toolchains("gcc")
    add_defines("HAIKU_HOST_PLATFORM")
end

-- ============================================================================
-- Build Modes
-- ============================================================================

add_rules("mode.debug")
add_rules("mode.release")

-- ============================================================================
-- Options
-- ============================================================================

option("target_arch")
    set_default("x86_64")
    set_showmenu(true)
    set_description("Target architecture")
    set_values("x86_64", "arm64", "riscv64")
option_end()

option("debug_level")
    set_default(0)
    set_showmenu(true)
    set_description("Debug level (0=release, 1=debug)")
option_end()

-- ============================================================================
-- Source Subdirectories
-- ============================================================================

-- Build libraries (host platform) - libbe_build.so, libshared_build.a
if os.isfile(path.join(HAIKU_TOP, "src", "build", "xmake.lua")) then
    includes(path.join(HAIKU_TOP, "src", "build", "xmake.lua"))
end

-- Build tools (host platform)
if os.isfile(path.join(HAIKU_TOP, "src", "tools", "xmake.lua")) then
    includes(path.join(HAIKU_TOP, "src", "tools", "xmake.lua"))
end

-- Main source tree
if os.isfile(path.join(HAIKU_TOP, "src", "xmake.lua")) then
    includes(path.join(HAIKU_TOP, "src", "xmake.lua"))
end
