/*
 * ThorVG Build Configuration for Haiku OS
 *
 * This file is intentionally empty.
 * All configuration is passed via compiler flags in Jamfile:
 * - THORVG_VERSION_STRING
 * - THORVG_SW_RASTER_SUPPORT
 * - THORVG_GL_RASTER_SUPPORT
 * - THORVG_THREAD_SUPPORT
 * - THORVG_FILE_IO_SUPPORT
 * - THORVG_SVG_LOADER_SUPPORT
 * - THORVG_LOTTIE_LOADER_SUPPORT
 * - THORVG_TTF_LOADER_SUPPORT
 * - THORVG_PNG_LOADER_SUPPORT
 * - THORVG_JPG_LOADER_SUPPORT
 * - THORVG_WEBP_LOADER_SUPPORT
 * - THORVG_GIF_SAVER_SUPPORT
 * - THORVG_CAPI_BINDING_SUPPORT
 * - THORVG_LOTTIE_EXPRESSIONS_SUPPORT
 * - THORVG_AVX_VECTOR_SUPPORT / THORVG_NEON_VECTOR_SUPPORT
 */

#ifndef _TVG_CONFIG_H_
#define _TVG_CONFIG_H_

#endif /* _TVG_CONFIG_H_ */